### PR TITLE
operator cockroachdb-certified (v2.4.0)

### PR DESCRIPTION
**Pull request by pseudomuto**

### CODE REVIEW

**Comment by tonytcampbell** [comment]
Going to run this again on our side.

**Comment by tonytcampbell** [comment]
Running this again on our side.

**Comment by tonytcampbell** [comment]
Please review the [instructions](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/hosted-pipeline.md) for submitting an operator bundle for certification.

**Comment by pseudomuto** [comment]
Hey @tonytcampbell thanks for the feedback. Is there particular step you noticed that was missed?

In the before you start section it says to:
> Complete the Project checklist in connect.redhat.com

The first step in that checklist is "Test your operator bundle data and submit a pull request". Is there a step I'm missing here?

**Comment by pseudomuto** [comment]
Progress! Test results are now available in partner connect

**Pull request merged**
