### PR TITLE
operator splunk-operator (2.5.1)

### PR DESCRIPTION
**Pull request by vivekr-splunk**
splunk operator 2.5.1 bundle

### CODE REVIEW

**Comment by vivekr-splunk** [comment]
can someone help me here to understand the issue. thank you

**Comment by SheryarButt** [comment]
Hi @vivekr-splunk, just reiterating the message from @acornett21 here for your help
I believe your operator is failing the `RequiredAnnotations` check. The CSV must be updated to include all of the following [annotations](https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs) and proper true/false values for each.

**Comment by acornett21** [comment]
@vivekr-splunk You can always log into your Red Hat connect account to see test failures, and pipeline logs. Your operator is failing the `RequiredAnnotations` check, like mentioned above.

**Pull request merged**
