### PR TITLE
operator tenant-operator (v0.5.2)

### PR DESCRIPTION
**Pull request by abdulhaseeb2**
**Features** 🚀:

- [x] Add support for tenant namespaces off-boarding. For more details check out [onDelete](https://docs.cloud.stakater.com/content/sre/tenant-operator/customresources.html#_2-tenant)
- [x] Add tenant webhook for spec validation

**Bug Fixes** 🐛:

- [x] TemplateGroupInstance now cleans up leftover Template resources from namespaces that are no longer part of TGI namespace selector
- [x] Fixed hibernation sync issue

**Enhancement**  🛠️ :

- [x] Update tenant spec for applying common/specific namespace labels/annotations. For more details check out [commonMetadata & SpecificMetadata](https://docs.cloud.stakater.com/content/sre/tenant-operator/customresources.html#_2-tenant)
- [x] Add support for multi-pod architecture for Operator-Hub

**Maintenance** 🚧 :

- [x] Remove conversion webhook for Quota and Tenant

### CODE REVIEW

**Comment by jsm84** [comment]
@abdulhaseeb2 please change the bundle directory name from `v0.5.2/` in your source branch to `0.5.2` as it's failing a regular expression check. The regex error below from the pipeline logs is due to enforcing semver 2.0 naming on the bundle directories:

```
[generate-index : generate] time="2022-07-26T07:46:00Z" level=error msg="permissive mode disabled" bundles="[quay.io/operator-pipeline-prod/tenant-operator:v0.5.2]" error="quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"
[generate-index : generate] Error: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
[generate-index : generate] Usage:
...
```

Your CSV contents look OK, so my first guess here is the bundle directory name cannot start with a `v`.

**Comment by abdulhaseeb2** [comment]
@jsm84 Thanks for the clarification, I've updated the bundle directory name and the PR name. Let's see if the pipeline passes. 😄

**Comment by jsm84** [comment]
@abdulhaseeb2 I may be off base here. @acornett21 informed me that other projects (and your previous submissions) have the preceding `v` in the bundle directory name.

I was looking at another operator example that I currently contribute to, as a reference, and I didn't see the `v` in the bundle directory name. That pattern certainly looks like it's matching a version number somewhere, it just doesn't say exactly where. Your `spec.version` string in the CSV looks fine, and the bundle directory name is the only other thing that stuck out (and seemed to break the regex pattern being matched).

We'll keep digging on this, and let you know if we find anything else. Fingers crossed that it goes through, however.

**Comment by abdulhaseeb2** [comment]
> @abdulhaseeb2 I may be off base here. @acornett21 informed me that other projects (and your previous submissions) have the preceding `v` in the bundle directory name.
> 
> I was looking at another operator example that I currently contribute to, as a reference, and I didn't see the `v` in the bundle directory name. That pattern certainly looks like it's matching a version number somewhere, it just doesn't say exactly where. Your `spec.version` string in the CSV looks fine, and the bundle directory name is the only other thing that stuck out (and seemed to break the regex pattern being matched).
> 
> We'll keep digging on this, and let you know if we find anything else. Fingers crossed that it goes through, however.

I think `v` is correct because in the [docs](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/troubleshooting.md#annotations-validation) it says that either keep `v` or don't but PR name and bundle dir name should be consistent

**Comment by acornett21** [comment]
@abdulhaseeb2 Have you tried to validate the bundle? Or deploy this operator to a cluster? I get the below error, not sure what is wrong in the CSV
```
./bin/operator-sdk bundle validate quay.io/operator-pipeline-prod/tenant-operator:v0.5.2
INFO[0000] Unpacking image layers                       
INFO[0000] running /usr/local/bin/docker pull quay.io/operator-pipeline-prod/tenant-operator:v0.5.2 
INFO[0002] running docker create                        
INFO[0002] running docker cp                            
INFO[0002] running docker rm                            
FATA[0002] [error loading objs in directory: unable to parse CSV tenant-operator.clusterserviceversion.yaml: error unmarshaling JSON: while decoding JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', no bundle csv found, unable to load bundle from directory /var/folders/9w/xqjxxz8927qd47f29dt49jsw0000gn/T/bundle-1505289665/manifests] 

```

**Comment by abdulhaseeb2** [comment]
> @abdulhaseeb2 Have you tried to validate the bundle? Or deploy this operator to a cluster? I get the below error, not sure what is wrong in the CSV
> 
> ```
> ./bin/operator-sdk bundle validate quay.io/operator-pipeline-prod/tenant-operator:v0.5.2
> INFO[0000] Unpacking image layers                       
> INFO[0000] running /usr/local/bin/docker pull quay.io/operator-pipeline-prod/tenant-operator:v0.5.2 
> INFO[0002] running docker create                        
> INFO[0002] running docker cp                            
> INFO[0002] running docker rm                            
> FATA[0002] [error loading objs in directory: unable to parse CSV tenant-operator.clusterserviceversion.yaml: error unmarshaling JSON: while decoding JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', no bundle csv found, unable to load bundle from directory /var/folders/9w/xqjxxz8927qd47f29dt49jsw0000gn/T/bundle-1505289665/manifests] 
> ```

So this release has a major change in which we are moving from a single pod operator to multi-pod controllers. After much copy-paste and `bundle validate` found the issue. 
```
resources:
  limits:
    limits:
      cpu: 2000m
      memory: 2Gi
```
😄

**Pull request merged**
