### PR TITLE
operator runtime-fabric-operator (v2.1.0)

### PR DESCRIPTION
**Pull request by digvijaysk19**

### CODE REVIEW

**Comment by digvijaysk19** [comment]
Thanks @jfrancin and @acornett21 for all the help! 
I think this time all the checks will go through!
Thanks a lot!!

**Comment by jfrancin** [comment]
You're welcome. Let's not count the chickens until they've completely hatched...

**Comment by jfrancin** [comment]
@digvijaysk19 there's a couple of things wrong with your bundle still:

a) Your previous bundle had:  com.redhat.openshift.versions: v4.6-v4.11
Your current bundle has com.redhat.openshift.versions: v4.6-v4.10

Is this intentional?

**Comment by digvijaysk19** [comment]
> @digvijaysk19 there's a couple of things wrong with your bundle still:
> 
> a) Your previous bundle had: com.redhat.openshift.versions: v4.6-v4.11 Your current bundle has com.redhat.openshift.versions: v4.6-v4.10
> 
> Is this intentional?

@jfrancin This is just a part of description, isn't it? runtime-fabric currently supports k8s 1.23 officially and OpenShift 4.11 has k8s 1.24. So that is why we just wanted to show v4.6 to v4.10 in the description. But we have used operator-jdk that supports 4.11. Is this a problem? We can make it v4.6-v4.11 if that is the cause of failure.

**Comment by digvijaysk19** [comment]
> replaces

I have not understood this one - I have used ```replaces``` in csv. https://github.com/digvijaysk19/certified-operators/blob/3164d40d346966fe49913e3119374ca178734679/operators/runtime-fabric-operator/v2.1.0/manifests/runtime-fabric-operator.clusterserviceversion.yaml#L388

**Comment by jfrancin** [comment]
No, it's not a description - it controls which versions of OpenShift's OperatorHub will be distributed. Everything in annotations.yaml is vitally important to get right.

**Comment by jfrancin** [comment]
As to 'replaces' - that keyword requires that the version being replaced must already exist in that particular version's OperatorHub index - and that will break with OpenShift v4.12, as due to the deprecated APIs, you won't have either v2.0.0 or v2.1.0 in the v4.12 index. 

Therefore, you should change the replaces keyword to 'skips' instead. The skips keyword does not require the pre-existence of any of the skipped versions in a given OpenShift version's index.

We can make both of these fixes for you if you want.

**Comment by digvijaysk19** [comment]
> 

Sure, we can replace it to ```com.redhat.openshift.versions: v4.6-v4.11``` in annotations.yaml
Should I do that, or will you do that?

**Comment by jfrancin** [comment]
I'll do it.

**Comment by jfrancin** [comment]
There's also a typo for e-mail in the CSV that we'll also fix.

**Comment by digvijaysk19** [comment]
> As to 'replaces' - that keyword requires that the version being replaced must already exist in that particular version's OperatorHub index - and that will break with OpenShift v4.12, as due to the deprecated APIs, you won't have either v2.0.0 or v2.1.0 in the v4.12 index.
> 
> Therefore, you should change the replaces keyword to 'skips' instead. The skips keyword does not require the pre-existence of any of the skipped versions in a given OpenShift version's index.
> 
> We can make both of these fixes for you if you want.

We need an upgrade path from v2.0.0 to v2.1.0 and In future, 2.1.0 to next one. Will this change affect any of these requirements?

**Comment by digvijaysk19** [comment]
> 

sure, thanks! Is it the key name?

**Comment by digvijaysk19** [comment]
> sure, thanks! Is it the key name?

sure, thanks! Is it the key name?

**Comment by jfrancin** [comment]
a) the e-mail typo is to remove the "-" before the 2nd key name.
b) It will provide the same upgrade path as 'replaces', but without the pre-existing previous bundle version requirement.

**Comment by digvijaysk19** [comment]
> a) the e-mail typo is to remove the "-" before the 2nd key name. b) It will provide the same upgrade path as 'replaces', but without the pre-existing previous bundle version requirement.

Sounds good! Thanks @jfrancin!

**Comment by jfrancin** [comment]
I need to break for a (very late) lunch, as does @acornett21 (it's normal lunch time for him, in MST; I'm in EST and should have had lunch hours ago. We will keep at this for you.

**Comment by digvijaysk19** [comment]
> 

Thank you so much @jfrancin! Really appreciate your help.

**Comment by digvijaysk19** [comment]
Is it not liking ```skips``` ?

**Comment by acornett21** [comment]
> Is it not liking `skips` ?

@digvijaysk19 I updated the CSV, `skips` is a list, see more about replace, skips, skipRange [here](https://olm.operatorframework.io/docs/concepts/olm-architecture/operator-catalog/creating-an-update-graph/#skips)

**Comment by digvijaysk19** [comment]
I believe an indentation this time.

**Comment by acornett21** [comment]
> I believe an indentation this time.

The indention was correct, there is a trailing space. I'll fix it one min.

**Comment by digvijaysk19** [comment]
Thank you @jfrancin and @acornett21 for all the help in getting this operator certified!
Learned so many things today. 
I think, we have to use same project id for future releases, don't we?

**Comment by acornett21** [comment]
> Thank you @jfrancin and @acornett21 for all the help in getting this operator certified! Learned so many things today. I think, we have to use same project id for future releases, don't we?

No problem. Happy to help. The project id does not need to change in the `ci.yaml` file going forward. You can just add new `version` folders to this directory.

**Pull request merged**
