### PR TITLE
operator aqua-operator-certified (v6.2.21293)

### PR DESCRIPTION
**Pull request by yossig-aquasec**
first operator

### CODE REVIEW

**Comment by tonytcampbell** [comment]
Hello. Question.  Does your operator happen to support OpenShift 4.8?

**Comment by yossig-aquasec** [comment]
Currently not, just 4.5-4.7

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tonytcampbell** [comment]
If you haven't already, would you mind opening a support case for this Certification.  I'm hoping we can connect there where I can share more information.  [Support Case](https://connect.redhat.com/support/technology-partner/#/case/new?type=CERT&source=tekton&cert_project_id=5f5b9a3134657b5bd5432395&cert_project_type=Operator%20Bundle%20Image&pull_request_url=https%3A%2F%2Fgithub.com%2Fredhat-openshift-ecosystem%2Fcertified-operators%2Fpull%2F117).

**Comment by yossig-aquasec** [comment]
I already opened 2 weeks ago, still no real and useful answer

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tonytcampbell** [comment]
What's the support case#?

**Comment by yossig-aquasec** [comment]
> What's the support case#?

Case 03070111

**Pull request merged**
