### PR TITLE
operator prometurbo-certified (8.12.20-beta.1)

### PR DESCRIPTION
**Pull request by turbodeploy**
prometurbo-certified-8.12.20 bundle

### CODE REVIEW

**Comment by SumanthKodali999** [comment]
@jfrancin  - May I know what's happening with this PR? The PR has hosted-pipeline status success but didn't get merged and publish to index

**Comment by jfrancin** [comment]
@SumanthKodali999 I had to hand-trigger the release pipeline for this PR.  I'll be asking Engineering about this.

**Comment by SumanthKodali999** [comment]
@jfrancin - PR is still open?

**Comment by jfrancin** [comment]
Looks like the auto-merge didn't, so I just did so...

**Comment by jfrancin** [comment]
Seems there was a GitHub-wide API outage: https://www.githubstatus.com/incidents/7txcg0j03kkg.
This one was affected by it.

**Pull request merged**
