### PR TITLE
operator mantaflow-operator (v36.0.0)

### PR DESCRIPTION
**Pull request by Mantatools**

### CODE REVIEW

**Comment by taylorjordanNC** [comment]
Be sure to follow the instructions in order to properly title your PR. See here:  https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/hosted-pipeline.md#step-3-create-a-pull-request

The PR title should be: "operator mantaflow-operator (v36.0.0)"

**Comment by Mantatools** [comment]
Thank you. I fixed the title accordingly.

**Comment by taylorjordanNC** [comment]
All of your images must be pinned with a SHA-256 hash.

**Comment by taylorjordanNC** [comment]
It's throwing an error for this image: registry.access.redhat.com/ubi8-minimal@sha256:27a3683c44e97432453ad25bf4a64d040e2c82cfe0e0b36ebf1d74d68e22b1c6

Can you verify this reference is correct?

**Comment by Mantatools** [comment]
Closing this pull request.

**Pull request closed without merging**
