### PR TITLE
operator instana-agent-operator (v2.0.0)

### PR DESCRIPTION
**Pull request by mdonkers**
Signed-off-by: Miel Donkers <miel.donkers@instana.com>

### CODE REVIEW

**Comment by rocrisp** [comment]
I think the PID : 5f60d64d39db392c95c0712e is mismatched with your package name,  instana-agent-operator.
Please make sure your package name is unique to your PID.

**Comment by mdonkers** [comment]
@rocrisp Thanks for responding.
The PID `5f60d64d39db392c95c0712e` is for the Bundle. The original PID `5e961c2c93604e02afa9ebdf` is for our Operator container image. If we use that, other checks fail because the GitHub users can't be retrieved (failing the `get-cert-project-related-data` check).

I cannot change the name for the Operator Container Image project because it has published images (at least not the "outbound" name). And the name for the Operator Bundle project is changed to `instana-agent-operator` but with no effect.
Also, for the Marketplace project all names should be aligned correctly but even there the same check is failing: https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/pull/18#issuecomment-972941002

Any other ideas what might need changing?

**Comment by rocrisp** [comment]
@mdonkers, I'm wondering if 5fc350a1-9257-4291-9f2a-df9257b9e791 is the correct PID ?
I'm hesitant because your projects's id and the Unique identifier are different.
Just for grins, could you try changing to 5fc350a1-9257-4291-9f2a-df9257b9e791 ?

**Comment by rocrisp** [comment]
@mdonkers I've related the message to our support team. Will let you know as soon as I have an answer. Hold tight!

**Comment by rocrisp** [comment]
Can you try using the package name instana-agent? 
The id 5f60e327dd19c7610a896276 is associated with the package name instana-agent.

This is how I found it and also verified with another team member. 
curl https://catalog.redhat.com/api/containers/v1/operators/packages?filter=package_name=="instana-agent"
{
  "data": [
    {
      "_id": "5f60e327dd19c7610a896276",
      "association": "ospid-5fc350a1-9257-4291-9f2a-df9257b9e791",
      "creation_date": "2020-09-15T15:52:07.240000+00:00",
      "last_update_date": "2020-09-15T15:52:07.240000+00:00",
      "package_name": "instana-agent",
      "source": "certified-operators"
    }
  ],

**Comment by mdonkers** [comment]
@rocrisp okay, it gets further now. Guess the current failure is because of in the same PR also changing a file in `instana-agent-operator`.
But, I'd rather use `instana-agent-operator` instead of `instana-agent`, as it would be more consistent in all files, and also how we deliver the "community operator": https://github.com/k8s-operatorhub/community-operators/tree/main/operators/instana-agent-operator

**Comment by rocrisp** [comment]
Let me see if someone can change the package name from under the covers. Will get back to you.

**Pull request merged**
