### PR TITLE
operator stackgres-certified (1.11.0-rc1)

### PR DESCRIPTION
**Pull request by teoincontatto**

### CODE REVIEW

**Comment by jinhli** [comment]
@teoincontatto, I saw you tried to update the package names in annotations.yaml and csv file to pass the test. 
I am sorry to tell you that, there is a known failure here if the package name in annotations.yaml is not the same as you set in csv file, the tool would throw the error `"Operator name from annotations.yaml (stackgres-certified) does not match the name defined in the CSV (stackgres)"`. That is expected. We can add a skip lable to pass the test to keep the package name  is same as you set before.

So please still use **"stackgres-certified"** in annotations.yaml, and **stackgres.v1.11.0-rc1** in  csv file. We will use the backaround to pass the test.

**Comment by teoincontatto** [comment]
@jinhli, I've reverted the change. Thanks for the support!

**Comment by jinhli** [comment]
@teoincontatto I added the skip lable to pass check-operator-name,, but it failed with evaluate-preflight-result. But I can deploy this operator on my cluster. So let me trigger it again

**Comment by jinhli** [comment]
@teoincontatto  it seems there is an issue in the backend service, let me check with internal team.

**Pull request merged**
