### PR TITLE
operator cloud-native-postgresql (1.15.2)

### PR DESCRIPTION
**Pull request by sxd**
fix: remove `null` channel on cloud-native-postgresql

Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>

### CODE REVIEW

**Comment by jfrancin** [comment]
You cannot update an existing, already published operator bundle. This will be rejected by the automation.

**Comment by sxd** [comment]
@jfrancin then how can we remove the `null` channel in that release?

**Comment by jfrancin** [comment]
You cannot. It will not be auto-selected during upgrade; a customer has to manually change channels from the default. It's no different, actually, than the v1.15-stable channel: a customer on that channel will not be able to upgrade to v1.16 until they change the channel to it.

**Comment by jfrancin** [comment]
I explained this in a comment to the support case you opened earlier today.

**Pull request closed without merging**
