### PR TITLE
operator intel-device-plugins-operator (0.28.0)

### PR DESCRIPTION
**Pull request by hershpa**
operator intel-device-plugins-operator (0.28.0)
Signed-off-by: Hersh Pathak [hersh.pathak@intel.com](mailto:hersh.pathak@intel.com)

### CODE REVIEW

**Comment by jsm84** [comment]
Looks like 0.26.2 was also missing from the v4.14 index. I've manually added that to v4.15 already, but I will go ahead and do the same for v4.15.

**Comment by hershpa** [comment]
@jsm84 we cannot see the operator on a OCP 4.13 and 4.14 cluster yet. On the connect portal, we see the PR as till open and not merged like we see here.

**Comment by jsm84** [comment]
@hershpa I'm working on that. I just published the 0.26.2 bundle to v4.15, which was holding up the release-pipeline.

Merge status (Open/Merged) doesn't reflect the availability of the operator, unfortunately. It's the release-pipeline that runs post-merge, which updates pyxis and makes the operator available through OperatorHub.

**Comment by jsm84** [comment]
I'm afraid the release-pipeline will fail again. The bundle v0.26.2 is not in v4.13 either, so this will also fail if v4.13 falls within the supported version range.

**Comment by hershpa** [comment]
Thanks @jsm84. Keep us posted.

**Comment by hershpa** [comment]
Thanks @jsm84!

**Comment by chaitanya1731** [comment]
Hi @jsm84  Thanks for fixing this.. now we can see the new operator in the 4.13 and 4.14 clusters... However, on the connect portal we still see that the PR is open and perhaps it still didn't update the "upgrade graph" yet.. can you please take a look at the same?

**Comment by hershpa** [comment]
> Hi @jsm84 Thanks for fixing this.. now we can see the new operator in the 4.13 and 4.14 clusters... However, on the connect portal we still see that the PR is open and perhaps it still didn't update the "upgrade graph" yet.. can you please take a look at the same?

+1 to this

**Pull request merged**
