### PR TITLE
removed dell-csi-operator-certified

### PR DESCRIPTION
**Pull request by shefali-malhotra**
Depricating dell-csi-operator

### CODE REVIEW

**Comment by Allda** [comment]
@shefali-malhotra The removal action is only allowed for operators that are using FBC. If you want to remove your operator you need to convert it to a FBC first. More info about the FBC can be found in an announcement with step-by-step process on how to convert it. https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/5031

**Comment by jinhli** [comment]
@Allda  i have removed this operator from operator hub.  So the only pending item is to remove the corresponding files from github. Is it necessary for them to convert it to a FBC?

**Comment by Allda** [comment]
Given @jinhli removed the operator manually from the index I will merge this PR to remove files from git repo.

**Comment by jinhli** [comment]
@Allda thanks for your support!

**Pull request merged**
