### PR TITLE
Revert PR hazelcast-platform-operator (5.12.0)

### PR DESCRIPTION
**Pull request by devOpsHelm**
This reverts commit f037a0ac8839c9226fcb67361396643b833148c0.

Signed-off-by: devOpsHelm devopshelm@hazelcast.com

### CODE REVIEW

**Comment by devOpsHelm** [comment]
@jfrancin Hello John can you help me to merge this PR? We need to revert PR and remove "hazelcast-platform-operator-5.12.0"

**Comment by devOpsHelm** [comment]
@jfrancin Hello John can you help me to merge this PR? We need to revert PR and remove "hazelcast-platform-operator-5.12.0"

**Comment by jfrancin** [comment]
This is the same issue as #4444 in the Community index. To remove this bundle requires removing the entire _bundle stream_ for hazelcast-platform-operator, re-adding every version up to but not including 5.12.0, and also unpublishing it from the Catalog. This is manual, time-consuming, and error-prone.

Quoting from the comment there:

> What you are asking for is not just a revert of a commit in a git repo: your previous PR was already processed by the release pipeline which updated the operator index of each supported openshift version to include the 5.12.0 bundle (that's what the operator-release-pipeline/passed label in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4442 means).
> Undoing that would require manually altering 5 different operator indices, one for each supported openshift version, which is a slow, complex and very error prone operation when done manually.
> 

Why can't you do a 5.12.1 with an appropriate 'skips' directive in the CSV?

**Comment by hasancelik** [comment]
Hi @jfrancin,

Thanks for your answer. I see the technical difficulties on your side.

> Why can't you do a 5.12.1 with an appropriate 'skips' directive in the CSV?

Because we need to release a new version of my docker image, helm chart, document, roadmap, etc. And also, as I mentioned at other PR, it will create confusion on the customer side.

Can you please provide any feedback or comments regarding my question on the PR section of the community?
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4444#issuecomment-2093163861

**Comment by jfrancin** [comment]
It will be up to the community maintainers to deal with your operator there.  Certification Operations only deals with the Certified and Marketplace operators.

I'm going to merge your removal now.

**Comment by hasancelik** [comment]
@jfrancin 

> I'm going to merge your removal now.

Would you mind confirming that you intend to carry out all the steps that you mentioned earlier?👇 

> To remove this bundle requires removing the entire bundle stream for hazelcast-platform-operator, re-adding every version up to but not including 5.12.0, and also unpublishing it from the Catalog. This is manual, time-consuming, and error-prone.

**Comment by jfrancin** [comment]
In the case of the Certified Operators, there was only one (1) operator because your CSV uses none of Skips, SkipRange or Replaces. Thus the default behavior is to simply replace the old version in the bundle index with the new one. No history is kept.

**Pull request merged**
