### PR TITLE
operator lenovo-locd-operator (v0.1.0)

### PR DESCRIPTION
**Pull request by xujt5**

### CODE REVIEW

**Comment by jinhli** [comment]
Hi @xujt5  I checked the preflight.stderr, and I found the following error, the tool falied with "ValidateOperatorBundle", please add the content  in CSV file .

  icon:
  - base64data: ""
    mediatype: ""


time="2022-08-22T09:45:46Z" level=error msg="Error: Value : (locd-operator.v0.0.1) csv.Spec.Icon elements should contain both data and mediatype"

**Comment by jinhli** [comment]
BTW, I checked the annotations.yaml, it missed the default channel. Please also add it.

  operators.operatorframework.io.bundle.channel.default.v1: alpha

**Comment by xujt5** [comment]
> BTW, I checked the annotations.yaml, it missed the default channel. Please also add it.
> 
> operators.operatorframework.io.bundle.channel.default.v1: alpha

**Comment by xujt5** [comment]
> Hi @xujt5 I checked the preflight.stderr, and I found the following error, the tool falied with "ValidateOperatorBundle", please add the content in CSV file .
> 
> icon:
> 
> * base64data: ""
>   mediatype: ""
> 
> time="2022-08-22T09:45:46Z" level=error msg="Error: Value : (locd-operator.v0.0.1) csv.Spec.Icon elements should contain both data and mediatype"

**Comment by jinhli** [comment]
@xujt5  I tried to deploy this operator from my cluster, and I saw the error message about pod of locd-operator-controller-manager: 
    - name: manager
      state:
        waiting:
          reason: CreateContainerError
          message: >
            container create failed: time="2022-08-24T03:58:30Z" level=error
            msg="container_linux.go:380: starting container process caused:
            exec: \"--health-probe-bind-address=:8081\": executable file not
            found in $PATH"

It seems that there is some error in the operator image  registry.connect.redhat.com/loc-devops/operator@sha256:65142a36095188e879467038936b7b6b6ee39dcea6d42a437fa7066fb2bc0f44

**Comment by xujt5** [comment]
> @xujt5 I tried to deploy this operator from my cluster, and I saw the error message about pod of locd-operator-controller-manager: - name: manager state: waiting: reason: CreateContainerError message: > container create failed: time="2022-08-24T03:58:30Z" level=error msg="container_linux.go:380: starting container process caused: exec: "--health-probe-bind-address=:8081": executable file not found in $PATH"
> 
> It seems that there is some error in the operator image registry.connect.redhat.com/loc-devops/operator@sha256:65142a36095188e879467038936b7b6b6ee39dcea6d42a437fa7066fb2bc0f44

Thanks for your help.
I have check the issue and found it is operator images problem and I have fixed the issue and republish the operator image. I will close this PR and reopen another one.

**Pull request closed without merging**
