### PR TITLE
operator eginnovations-operator (0.0.3)

### PR DESCRIPTION
**Pull request by gsreg**

### CODE REVIEW

**Comment by jinhli** [comment]
@gsreg I found you have submitted this version(0.0.3) with https://github.com/redhat-openshift-ecosystem/certified-operators/pull/1554. Could you let us know why you want to submit an pr for the same version?
If you want to fix an issue, I would suggest you to bump a new version.

**Comment by gsreg** [comment]
actually this version #1554 is not installing over oc 4.11, because of this ```allowPrivilegeEscalation: true``` which is need to be false. This PR only contain this false flag and little description changes nothing image related changes are present. And the same version is also released over community repo [#1862](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1862).

**Comment by jinhli** [comment]
@gsreg if you wants to fix something in the merged version,  the best way to fix it is to submit a new bundle with a working CSV that skips the broken one by adding a spec.skips field to the CSV

spec:
...
  skips:
  - <bad CSV version>
  version: <new version>

**Comment by gsreg** [comment]
@jinhli is there way to delete a version of this operator.

**Comment by jinhli** [comment]
@gsreg I could not delete the version of the operator. It needs the support from the engineering team. And deleting is not a good way, so we suggest you submit a new version to fix it.

**Comment by gsreg** [comment]
@jinhli ok i'll submit PR for new release

**Pull request closed without merging**
