### PR TITLE
operator mongodb-enterprise (1.25.0)

### PR DESCRIPTION
**Pull request by nammn**
Signed-off-by: Nam Nguyen nam.nguyen@mongodb.com{code}

### CODE REVIEW

**Comment by jfrancin** [comment]
Unfortunately, the /pipeline restart operator-release-pipeline doesn't work if it's never been run for this PR.  I've just triggered the release pipeline for this PR.

**Comment by mircea-cosbuc** [comment]
> Unfortunately, the /pipeline restart operator-release-pipeline doesn't work if it's never been run for this PR. I've just triggered the release pipeline for this PR.

Thank you!

**Pull request merged**
