### PR TITLE
operator kove-operator (v2.1.0)

### PR DESCRIPTION
**Pull request by kove-development**
**New operator bundle**

Name: **kove-operator**
Version: **v2.1.0**

Certification project: 615d2d4d2d5a5137e913e4ff

Test result URL: https://catalog.redhat.com/api/containers/v1/projects/certification/test-results/id/
Test logs URL: https://catalog.redhat.com/api/containers/v1/projects/certification/artifacts/id/662fe8486d8db6071233c36c

### CODE REVIEW

**Comment by jinhli** [comment]
I found the new bundle index was not created https://quay.io/repository/operator-pipeline-prod/kove-operator-index?tab=tags, so re-trigger it to see

**Comment by acornett21** [comment]
> I found the new bundle index was not created https://quay.io/repository/operator-pipeline-prod/kove-operator-index?tab=tags, so re-trigger it to see

@jinhli Images are no longer stored there, they are in a single `namespace` now, if you can see the pipeline created the below image and it's avilable.
`quay.io/operator-pipeline-prod/catalog:v4.15-2a50da38d3cfcc794eab7709038fd92dce0a567c`

This operator is failing  `DeployableByOLM` did anyone verify that it actually works?

**Comment by kove-development** [comment]
@acornett21 
This was our description from the Partner Acceleration Desk support case we opened (03805511)

> The Preflight check DeployableByOLM is consistently passing when running the certification test suite locally and failing in the Red Hat Hosted Pipeline. The DeployableByOLM check has passed in the Red Hat Hosted Pipeline when certifying previous operator versions.
> 
> The DeployableByOLM check does not provide enough debug output to determine why it is failing. There are no significant changes in this operator version that could plausibly cause this check to fail only in the Red Hat Hosted Pipeline.
> 
> Our best guess is that the Red Hat Hosted Pipeline might be failing to pull the operator image when the DeployableByOLM check creates the subscription. The operator image is in a private repository on quay.io, and the pull secret for this private repository has been added to the OpenShift Object YAML in the Operator Bundle configuration in the Certification Portal.

**Comment by acornett21** [comment]
@kove-development I think I see the issue, the `Hosted` pipeline is running because you are running the CI pipeline, but with an older version of preflight, so there are no successful results in our system for you CI run.

```
[upload-artifacts : upload-test-results] 2024-04-29 18:34:55,450 [operator-cert] ERROR Pyxis POST query failed with https://catalog.redhat.com/api/containers/v1/projects/certification/id/615d2d4d2d5a5137e913e4ff/test-results - 400 - {"detail": "Validation error: 'github.com/redhat-openshift-ecosystem/openshift-preflight' version '1.8.0' is not supported. Supported versions are: ['1.9.1', '1.9.2']", "status": 400, "title": "Bad Request", "type": "about:blank", "trace_id": "0x657dcb11453e2179be758e634a2523f1"}
```

Can you update the  CI pipeline tasks in your cluster with the latest release? I'm going to close this PR, so a new CI run will re-create a new PR.

**Pull request closed without merging**
