### PR TITLE
operator cilium-enterprise (v1.11.14)

### PR DESCRIPTION
**Pull request by michi-covalent**

### CODE REVIEW

**Comment by mrhillsman** [comment]
@michi-covalent please stop opening and closing at this time

**Comment by michi-covalent** [comment]
sure! please let me know how i should proceed 🙏

**Comment by jfrancin** [comment]
After you closed #1931, I re-ran #1933.  It failed in verify-ci-results.  Basically it couldn't deploy the bundle.

I noted that you have a typo in the CSV file: you have "replace: <old-version>" instead of "replaces: <old-version>". Try fixing that and resubmitting.

**Comment by michi-covalent** [comment]
thanks @jfrancin! i'll update the pull request ✅

**Pull request closed without merging**
