### PR TITLE
operator hspc-operator (1.14.0)

### PR DESCRIPTION
**Pull request by joseperez-10**
updated operator

### CODE REVIEW

**Comment by joseperez-10** [comment]
trying one more time

**Comment by acornett21** [comment]
This did not merge, since merge is set to false in the `ci.yaml` file.

**Comment by joseperez-10** [comment]
Thanks, no need to merge since this is part of the cert for the beta version 1.14.

**Comment by joseperez-10** [comment]
updated the ci.yaml to allow merge

**Pull request merged**
