### PR TITLE
operator cilium (v1.11.14)

### PR DESCRIPTION
**Pull request by michi-covalent**

### CODE REVIEW

**Comment by michi-covalent** [comment]
`preflight-trigger` failed with this error message. how do i fix this? 
```
[preflight-trigger : create-openshift-ci-prowjob] /tekton/scripts/script-1-4fztj: line 25: /usr/local/bin/preflight-trigger: No such file or directory
```

**Comment by michi-covalent** [comment]
re-triggering to see if it helps

**Comment by michi-covalent** [comment]
thank you for taking care of this @mrhillsman!

just for my future reference: do i just re-trigger if i hit the same issue, or did you have to do some extra stuff for the test to pass?

**Comment by mrhillsman** [comment]
@michi-covalent I would recommend reaching out to someone directly if you are seeing errors in preflight-trigger if it is not resolved after a few runs.

**Pull request merged**
