### PR TITLE
operator aikit-operator (2023.1.0)

### PR DESCRIPTION
**Pull request by sharvil10**
AiKit Operator added for 2023.1.0

### CODE REVIEW

**Comment by jsm84** [comment]
@sharvil10 This is failing to actually publish to the OpenShift v4.10 certified index.

This bundle replaces `aikit-operator.v2021.2.102120`, which is not even published in v4.10 (which has v2022.3.x versions only).

Is it your intent to add this to OpenShift v4.10 also? That may not be possible unless we delete all the v2022.3 versions from that index.

**Comment by sharvil10** [comment]
> @sharvil10 This is failing to actually publish to the OpenShift v4.10 certified index.
> 
> This bundle replaces `aikit-operator.v2021.2.102120`, which is not even published in v4.10 (which has v2022.3.x versions only).
> 
> Is it your intent to add this to OpenShift v4.10 also? That may not be possible unless we delete all the v2022.3 versions from that index.

I am working on fixing this. As of now we have different versions of operators for different versions of OpenShift. For 4.7-4.10 we have `v2022.3.x` whereas for 4.11-4.13 we have `aikit-operator.v2021.2.102120`. Is there a way we can replace all versions with this latest version in 1 CSV PR?

**Comment by jsm84** [comment]
@sharvil10 If you do not care about the previous versions (and their upgrade ability) then you can just push this version without _any_ `skips` or `replaces` directives in the CSV, and it will effectively overwrite/erase the update graph and versioning will start over from 2023.1.0

**Comment by sharvil10** [comment]
@jsm84 thank you for the information. Since I can't edit the files that are already merged. I'll have to create a new PR. Is there any way for me to update the files that I already merged in this PR?

**Comment by jsm84** [comment]
@sharvil10 Unfortunately, due to the GH actions workflows you'll need to open two new PRs:
* One that removes this bundle directory 2023.1.0
* Another that provides the 2023.1.0 bundle directory, with the updated CSV file

I can submit the removal PR if you'd rather, and ping you on it once it merges.

**Comment by sharvil10** [comment]
@jsm84 if you could submit the removal PR that'll be really helpful. Thank you so much.

**Comment by jsm84** [comment]
@sharvil10 that is PR #2262 and it has already merged.

**Pull request merged**
