### PR TITLE
operator zabbix-operator-certified (6.0.13)

### PR DESCRIPTION
**Pull request by dotneft**
**New operator bundle**

Name: **zabbix-operator-certified**
Version: **6.0.13**

Certification project: 5f64d7cb9dd62e2eb63ccabd

Test result URL: https://catalog.redhat.com/api/containers/v1/projects/certification/test-results/id/6400b69e2a368a0a3332797c
Test logs URL: https://catalog.redhat.com/api/containers/v1/projects/certification/artifacts/id/6400b69b89895871c8ae366c

### CODE REVIEW

**Comment by jsm84** [comment]
@dotneft Looking into your support case, and from the looks of it v6.0.13 is _not_ in any version of the certified or marketplace index for OpenShift.

After inspection, this seems to be due to the 6.0.13 bundle missing a `spec.replaces` field in the clusterserviceversion yaml file. For this to show up correctly in the index, you must use `spec.replaces` and/or `spec.skips` fields to support an upgrade path for existing users.

Also, I'd caution against using the annotation `olm.skipRange` since it causes older releases to be removed from the index image (for whatever version of OpenShift), which is only useful for a "rebase" of sorts where you want to create a new base version that any previously installed release could update from, in a single hop.

**Comment by jfrancin** [comment]
@dotneft, Actually, it turned out to be an unsignalled error in the publishing process. I re-triggered the release pipeline, and then checked the v4.11 and v4.12 indexes - the bundle is now present.  It should also be present in v4.9 and v4.10 now too. I've just now re-triggered the Marketplace publication step as well.

**Comment by jsm84** [comment]
@dotneft I should also add, that looking at the CSV.yaml for this release will (or rather, did) wipe out the release history.

Bundles versioned 6.0.12 and older (including 0.0.3 which was the next oldest release) are gone from all versions of OpenShift 4.8 thru 4.12.

**Comment by dotneft** [comment]
So you recommend to use always spec.replaces instead of skip.ranges?

**Comment by dotneft** [comment]
Got it! Thank you for the explanation!

**Pull request merged**
