### PR TITLE
operator mongodb-atlas-kubernetes (1.4.0)

### PR DESCRIPTION
**Pull request by igor-karpukhin**

### CODE REVIEW

**Comment by jsm84** [comment]
This has already merged, but the post merge release-pipeline had a transient failure when publishing to the OpenShift v4.7 certified index.

I've tried to re-trigger this (which ordinarily would've resolved this), but OpenShift v4.7 index was marked to go EOL on 10/27/22.

Now we're seeing errors stating that OpenShift v4.7 has reached end of life (this is in the `get-supported-versions` task of the release-pipeline).

For this operator bundle, it means that it's not currently possible to publish to OpenShift v4.7 unless action is taken inside of Red Hat (where we have tickets open internally). The workaround is to have partners change from the legacy `com.redhat.openshift.versions` label values of `"v4.6"` and `"v4.5,v4.6"` in the interim, unless we can change the pipeline to gracefully ignore requests to publish to v4.7 (and v4.6, when it goes EOL).

**Comment by igor-karpukhin** [comment]
@jsm84 is the only way to update these fields is to bump up the operator version?

**Comment by jsm84** [comment]
@igor-karpukhin Please excuse as I've been out since Tuesday of last week. 

You can't bump them retroactively, unfortunately.

The way to go about it is to use push a new bundle version, and skip the old one using `spec.skips` in the CSV.

I'm attempting to work around the issue here by pushing the bundle to the certified index.

**Comment by jsm84** [comment]
@igor-karpukhin are you good to go? 

I just manually pushed v1.4.0 to all OCP releases (4.6 and later) but it looks like you've opened #1462 (with a version bump) and it looks to have merged, so the manual additions ended up being a no-op since 1.4.1 was already there.

**Comment by igor-karpukhin** [comment]
@jsm84 no worries! We recently release 1.4.1 with a fix for Openshift version. Thanks for your help!

**Pull request merged**
