### PR TITLE
operator vsphere-kubernetes-drivers-operator (0.1.0)

### PR DESCRIPTION
**Pull request by asifdxtreme**

### CODE REVIEW

**Comment by tonytcampbell** [comment]
Please review the [instructions](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/hosted-pipeline.md) for submitting an operator bundle for certification.

**Comment by asifdxtreme** [comment]
> Please review the [instructions](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/hosted-pipeline.md) for submitting an operator bundle for certification.

@tonytcampbell Thanks for pointing out to the guide, Just curious to know if there is any way to see the error logs to identify the failed tests?

**Comment by tonytcampbell** [comment]
> > Please review the [instructions](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/hosted-pipeline.md) for submitting an operator bundle for certification.
> 
> @tonytcampbell Thanks for pointing out to the guide, Just curious to know if there is any way to see the error logs to identify the failed tests?

You will be able to see logs in Connect but there is a known issue with that feature that we are working on at the moment.

**Comment by asifdxtreme** [comment]
> > > Please review the [instructions](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/hosted-pipeline.md) for submitting an operator bundle for certification.
> > 
> > 
> > @tonytcampbell Thanks for pointing out to the guide, Just curious to know if there is any way to see the error logs to identify the failed tests?
> 
> You will be able to see logs in Connect. There is a known issue with that feature that we are working on at the moment but you should have logs for your last attempt.

Thanks @tonytcampbell , currently we are not able to see even the last logs in Red Hat Connect Portal, I tried running the same thing in local hosted crc with minimal pipeline run, I am currently facing below problem
```
[yaml-lint : lint-yaml-files] [Errno 13] Permission denied: 'operators/vsphere-kubernetes-drivers-operator/0.1.0'
```
It would be great if you can help us to point out the issues with this

**Comment by taylorjordanNC** [comment]
@asifdxtreme Please change the namespace field in your CSV to "placeholder" instead of "vsphere-kubernetes-drivers-operator".

**Comment by taylorjordanNC** [comment]
@asifdxtreme Hello! There are some concerns around this Operator in future versions of OpenShift. I tried reaching out to the email from your account but it won't allow external emails. Can you please share an email address I can reach out to you with?

**Comment by asifdxtreme** [comment]
@taylorjordanNC you can contact us on smohammadasi@vmare.com for any queries related to this operator, we will be happy to make this compatible with future releases of Openshift

**Pull request merged**
