### PR TITLE
operator vfunction-server-operator (v2.3.594)

### PR DESCRIPTION
**Pull request by vfunction**
**New operator bundle**

Name: **vfunction-server-operator**
Version: **v2.3.594**

Certification project: 5f64dc1e0a4d06443d2818ad

Test result URL: https://catalog.redhat.com/api/containers/v1/projects/certification/test-results/id/61917043d115ef379a598e5e
Test logs URL: https://catalog.redhat.com/api/containers/v1/projects/certification/artifacts/id/61917042d6b39d004292bad1

### CODE REVIEW

**Comment by vfunction** [comment]
Hi,

I'm sure 100% that my ci tests passed okay (even 3 times...) on my local OpenShift cluster with the most updated operator-ci-pipeline.yml and tasks from the operator-pipelines repo.
I did have some issues with timeout exceeding on both ScorecardBasicSpecCheck & ScorecardOlmSuiteCheck before I updated. (I couldn't access the test result URL nor the logs URL from above to see the exact errors for this run - to be sure they are the same, though) 

Before starting the long journey of opening a support case for this, I just wanted to make sure that the errors are not on your end because the tests cluster is not updated correctly? Could you please verify that tests can pass at all now for ScorecardBasicSpecCheck & ScorecardOlmSuiteCheck on your testing cluster?

  Thanks.

**Comment by vfunction** [comment]
Now I could also see in the logs that both ScorecardBasicSpecCheck and ScorecardOlmSuiteCheck failed on the 30 seconds timeout (as I expected and mentioned in my previous comment).

As I also mentioned - I had this error too until I pulled a new version from operator-pipelines and applied all pipelines and tasks on the OpenShift cluster.


From the last Perflight.log:

time="2021-11-15T13:58:35Z" level=info msg="running check: ScorecardBasicSpecCheck"
time="2021-11-15T13:58:35Z" level=debug msg="Running operator-sdk scorecard check for quay.io/operator-pipeline-prod/vfunction-server-operator:v2.3.594"
time="2021-11-15T13:58:35Z" level=debug msg="--selector=[test=basic-check-spec-test]"
time="**2021-11-15T13:58:35Z**" level=trace msg="running scorecard with the following invocation[operator-sdk scorecard --output json --selector=test=basic-check-spec-test --kubeconfig /tmp/kubeconfig-3421170286 --namespace default --service-account default --config /tmp/scorecard-test-config-3472466720.yaml --verbose /tmp/preflight-3179944778/fs]"
time="**2021-11-15T13:59:05Z**" level=error msg="stdout: "
time="2021-11-15T13:59:05Z" level=error msg="stderr: time=\"2021-11-15T13:58:35Z\" level=debug msg=\"Debug logging is set\"\nError: error running tests context deadline exceeded\nUsage:\n  operator-sdk scorecard [flags]\n\nFlags:\n  -c, --config string            path to scorecard config file\n  -h, --help                     help for scorecard\n      --kubeconfig string        kubeconfig path\n  -L, --list                     Option to enable listing which tests are run\n  -n, --namespace string         namespace to run the test images in\n  -o, --output string            Output format for results. Valid values: text, json, xunit (default \"text\")\n  -l, --selector string          label selector to determine which tests are run\n  -s, --service-account string   Service account to use for tests (default \"default\")\n  -x, --skip-cleanup             Disable resource cleanup after tests are run\n  -b, --storage-image string     Storage image to be used by the Scorecard pod (default \"docker.io/library/busybox@sha256:c71cb4f7e8ececaffb34037c2637dc86820e4185100e18b4d02d613a9bd772af\")\n  -t, --test-output string       Test output directory. (default \"test-output\")\n  -u, --untar-image string       Untar image to be used by the Scorecard pod (default \"registry.access.redhat.com/ubi8@sha256:910f6bc0b5ae9b555eb91b88d28d568099b060088616eba2867b07ab6ea457c7\")\n  -w, --wait-time duration       seconds to wait for tests to complete. Example: 35s (default 30s)\n\nGlobal Flags:\n      --plugins strings   plugin keys to be used for this subcommand execution\n      --verbose           Enable verbose logging\n\ntime=\"2021-11-15T13:59:05Z\" level=fatal msg=\"**error running tests context deadline exceeded**\"\n"
time="2021-11-15T13:59:05Z" level=info msg="check completed: ScorecardBasicSpecCheck" ERROR="failed to run operator-sdk scorecard: exit status 1" result="failed to run operator-sdk scorecard: exit status 1"
time="2021-11-15T13:59:05Z" level=info msg="running check: ScorecardOlmSuiteCheck"
time="2021-11-15T13:59:05Z" level=debug msg="Running operator-sdk scorecard Check for quay.io/operator-pipeline-prod/vfunction-server-operator:v2.3.594"
time="2021-11-15T13:59:05Z" level=debug msg="--selector=[suite=olm]"
time="**2021-11-15T13:59:05Z**" level=trace msg="running scorecard with the following invocation[operator-sdk scorecard --output json --selector=suite=olm --kubeconfig /tmp/kubeconfig-3421170286 --namespace default --service-account default --config /tmp/scorecard-test-config-2813129432.yaml --verbose /tmp/preflight-3179944778/fs]"
time="**2021-11-15T13:59:36Z**" level=error msg="stdout: "
time="2021-11-15T13:59:36Z" level=error msg="stderr: time=\"2021-11-15T13:59:05Z\" level=debug msg=\"Debug logging is set\"\nError: error running tests context deadline exceeded\nUsage:\n  operator-sdk scorecard [flags]\n\nFlags:\n  -c, --config string            path to scorecard config file\n  -h, --help                     help for scorecard\n      --kubeconfig string        kubeconfig path\n  -L, --list                     Option to enable listing which tests are run\n  -n, --namespace string         namespace to run the test images in\n  -o, --output string            Output format for results. Valid values: text, json, xunit (default \"text\")\n  -l, --selector string          label selector to determine which tests are run\n  -s, --service-account string   Service account to use for tests (default \"default\")\n  -x, --skip-cleanup             Disable resource cleanup after tests are run\n  -b, --storage-image string     Storage image to be used by the Scorecard pod (default \"docker.io/library/busybox@sha256:c71cb4f7e8ececaffb34037c2637dc86820e4185100e18b4d02d613a9bd772af\")\n  -t, --test-output string       Test output directory. (default \"test-output\")\n  -u, --untar-image string       Untar image to be used by the Scorecard pod (default \"registry.access.redhat.com/ubi8@sha256:910f6bc0b5ae9b555eb91b88d28d568099b060088616eba2867b07ab6ea457c7\")\n  -w, --wait-time duration       seconds to wait for tests to complete. Example: 35s (default 30s)\n\nGlobal Flags:\n      --plugins strings   plugin keys to be used for this subcommand execution\n      --verbose           Enable verbose logging\n\ntime=\"2021-11-15T13:59:36Z\" level=fatal msg=\"**error running tests context deadline exceeded**\"\n"
time="2021-11-15T13:59:36Z" level=info msg="check completed: ScorecardOlmSuiteCheck" ERROR="failed to run operator-sdk scorecard: exit status 1" result="failed to run operator-sdk scorecard: exit status 1"

**Comment by tonytcampbell** [comment]
Thank you.  We are looking into this on our side.

**Comment by vfunction** [comment]
Hi,

Any news regarding this?

   Thanks.

**Pull request merged**
