### PR TITLE
operator runtime-component-operator-certified (1.3.2)

### PR DESCRIPTION
**Pull request by leochr**
**New operator bundle**

Name: **runtime-component-operator-certified**
Version: **1.3.2**

Certification project: 5f7f4aec9596965ec5efdac6

### CODE REVIEW

**Comment by leochr** [comment]
For future reference: support case for the `check_operator_name ` error: https://connect.redhat.com/support/technology-partner/#/case/03830816

**Comment by acornett21** [comment]
@jfrancin We should probably add this operator and the one linked below to the exclusion list. Though, I do not know if the value in the lists is for the `packagename` (from the annotations file) or the `name` from the CSV. LMK your thoughts.

- Relates: redhat-openshift-ecosystem/certified-operators#3964

**Pull request merged**
