### PR TITLE
operator runtime-fabric-operator (v2.2.5)

### PR DESCRIPTION
**Pull request by digvijaysk19**

### CODE REVIEW

**Comment by digvijaysk19** [comment]
@jfrancin @acornett21 Certification is failing due to preflight check failure for operator bundle. can you please help with this? I'll create a support case too. Thanks!

**Comment by jfrancin** [comment]
I've re-triggered the bundle cert now.

**Comment by digvijaysk19** [comment]
> I've re-triggered the bundle cert now.

Thank you so much @jfrancin, appreciate it!

**Comment by digvijaysk19** [comment]
Fyi, I have added "olm.properties": '[{"type": "olm.maxOpenShiftVersion", "value": "4.11"}]' as validation was complaining. Also, we need to block cluster upgrades to 4.12, as our current software version is not supported on k8s 1.25 yet.

**Comment by jfrancin** [comment]
Looks like there's a bug in Preflight where it's misinterpreting the olm.maxOpenShiftVersion field. Since this is v4.11 (kubernetes v1.24), it should allow any API that is deprecated in the _next_ version (i.e., v4.12). I'm referring this to Engineering to have a look.

**Comment by digvijaysk19** [comment]
> s deprecated in the _next_ version

Thanks @jfrancin!

**Comment by acornett21** [comment]
@digvijaysk19 Sorry for the delay, we should have a fix for this by later today.

**Comment by digvijaysk19** [comment]
Hello @acornett21, @jfrancin 
I still am facing the same issue - 

`time="2023-04-17T22:22:47Z" level=error msg="Error: Value : (runtime-fabric-operator.v2.2.5) invalid value for olm.maxOpenShiftVersion. The OCP version value 4.11 is >= of 4.9. Note that this bundle is using APIs which were deprecated and removed in v1.25. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25. Migrate the API(s) for cronjobs: ([\"ClusterServiceVersion.Spec.InstallStrategy.StrategySpec.ClusterPermissions[0].Rules[10]\"]),podsecuritypolicies: ([\"ClusterServiceVersion.Spec.InstallStrategy.StrategySpec.ClusterPermissions[0].Rules[4]\"])," error="validate operator bundle error"`

**Comment by acornett21** [comment]
@digvijaysk19 preflight's release was still running. I have moved the `stable` tag to point to the new release and the pipeline will pickup the new release. I also triggered the pipeline.

**Comment by digvijaysk19** [comment]
> @digvijaysk19 preflight's release was still running. I have moved the `stable` tag to point to the new release and the pipeline will pickup the new release. I also triggered the pipeline.

Thank you so much!!

**Comment by digvijaysk19** [comment]
> 

It is still picking up 1.6.0. Should re-try after sometime?

**Pull request merged**
