### PR TITLE
operator xspc-operator (1.8.0)

### PR DESCRIPTION
**Pull request by sidikinoel**
Pull Request for HPE xspc operator bundle

### CODE REVIEW

**Comment by jinhli** [comment]
Hi, 
Please use    
600fa52030b1d159e197b2e2 to instead 3c8d75d8-1f2f-48e0-bd51-ccde1e690a75 in ci.yaml

**Comment by sidikinoel** [comment]
> Hi, Please use 600fa52030b1d159e197b2e2 to instead 3c8d75d8-1f2f-48e0-bd51-ccde1e690a75 in ci.yaml

As you can see from the previous runs.  This cert project id also doesn't work.  I'll re-run to generate the logs.

**Comment by sidikinoel** [comment]
> 
----
reserve-operator-name
This step will make sure that the package name of our Operator belongs to your cert_project_id. This step will fail if another cert_project_id has laid claim to the package name used in this Pull Request.
----
Logs show:
---
[certification-project-check : certification-project-check] Checking availability of cert project identifier
[certification-project-check : certification-project-check] 600fa52030b1d159e197b2e2
[create-support-link-for-pr : create-support-link-for-pr] Follow this link if you wish to open a support case:
[create-support-link-for-pr : create-support-link-for-pr] https://connect.redhat.com/support/technology-partner/
----

@jinhli Could you provide insights on what other project has a claim on the operator package name?  I suspect this error is referring to package name xspc-operator.  The logs didn't provide much insight on this.  Thanks ahead.

**Comment by jinhli** [comment]
@sidikinoel I have updated the comment in case#03109725 according to your latest run. You could take a look and fix them before re-open the pr.

**Comment by jinhli** [comment]
@sidikinoel I have updated the comment in case#3109725 according to your latest run. You could take a look and fix them before re-open the pr.

**Pull request merged**
