### PR TITLE
operator zookeeper-operator (0.16.4)

### PR DESCRIPTION
**Pull request by streamnativebot**
Signed-off-by: streamnativebot streamnativebot@streamnative.io

### CODE REVIEW

**Comment by atiwary91** [comment]
Check you project checklist is completed or not?

**Comment by atiwary91** [comment]
Any reason why release pipeline is not getting triggered ?

**Comment by Allda** [comment]
> Any reason why release pipeline is not getting triggered ? cc @Allda

The release pipeline got triggered as you can see in the report.

**Comment by atiwary91** [comment]
I spoke early ,thanks

**Pull request merged**
