### PR TITLE
operator stackgres-certified (1.11.0)

### PR DESCRIPTION
**Pull request by teoincontatto**

### CODE REVIEW

**Comment by teoincontatto** [comment]
@jinhli seem we have the same problem as for `stackgres.v1.11.0-rc1`: https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3997#issuecomment-2154470393

Would be great for now to also add the skip annotation.

**Comment by jinhli** [comment]
> @jinhli seem we have the same problem as for `stackgres.v1.11.0-rc1`: [#3997 (comment)](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3997#issuecomment-2154470393)
> 
> Would be great for now to also add the skip annotation.

@teoincontatto  I added the label here.  Feel free to let me know if there is any issue.

**Comment by jinhli** [comment]
@teoincontatto there is a known issue about our backend service. Re-trigger is the workaround,  let me re-trigger it again.
You can see the log  in preflight.stderr.

check=DeployableByOLM err="could not list image streams: failed to get API group resources: unable to retrieve the complete list of server APIs: [image.openshift.io/v1](http://image.openshift.io/v1): the server is currently unable to handle the request" result=ERROR

**Pull request merged**
