### PR TITLE
operator cilium (v1.11.17)

### PR DESCRIPTION
**Pull request by thorn3r**

### CODE REVIEW

**Comment by thorn3r** [comment]
`generate-index` is failing at:
```
[generate-index : inspect-base-index] ++ echo registry.redhat.io/redhat/certified-operator-index:v4.14
[generate-index : inspect-base-index] ++ rev
[generate-index : inspect-base-index] ++ cut -f1 -d/
[generate-index : inspect-base-index] ++ rev
[generate-index : inspect-base-index] + INDEX_IMG_STREAM=certified-operator-index:v4.14
[generate-index : inspect-base-index] + FROM_INDEX=image-registry.openshift-image-registry.svc:5000/operator-pipeline-prod/certified-operator-index:v4.14
[generate-index : inspect-base-index] + podman pull image-registry.openshift-image-registry.svc:5000/operator-pipeline-prod/certified-operator-index:v4.14
[generate-index : inspect-base-index] Trying to pull image-registry.openshift-image-registry.svc:5000/operator-pipeline-prod/certified-operator-index:v4.14...
[generate-index : inspect-base-index] Error: initializing source docker://image-registry.openshift-image-registry.svc:5000/operator-pipeline-prod/certified-operator-index:v4.14: reading manifest v4.14 in image-registry.openshift-image-registry.svc:5000/operator-pipeline-prod/certified-operator-index: manifest unknown: manifest unknown

[generate-index : determine-index-format] 2023/05/23 16:56:49 Skipping step because a previous step failed
```
I'm not sure this is related to our changes, and the troubleshooting guide only covers operator upgrades to v4.9 which is not relevant in this case.

**Comment by thorn3r** [comment]
`preflight-trigger` is failing at:
```
[preflight-trigger : encrypt-and-encode-docker-config-json] 2023/05/23 20:37:52 Writing encoded data to file /workspace/credentials/project_dockerconfigjson.gpg.b64

[preflight-trigger : create-openshift-ci-prowjob] 2023/05/23 20:37:52 Validating job flags
[preflight-trigger : create-openshift-ci-prowjob] time="2023-05-23T20:37:52Z" level=info msg="Cannot use full value, will truncate." id= job=periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.12-preflight-prod-claim key=prow.k8s.io/job maybeTruncated=periodic-ci-redhat-openshift-ecosystem-certified-operators-prod value=periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.12-preflight-prod-claim
[preflight-trigger : create-openshift-ci-prowjob] 2023/05/23 20:37:53 Waiting for prowjob status...
[preflight-trigger : create-openshift-ci-prowjob] &{ArtifactsURL:origin-ci-test/logs/periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.12-preflight-prod-claim/1661109213088190464 Status:failure URL:https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-openshift-ecosystem-certified-operators-prod-ocp-4.12-preflight-prod-claim/1661109213088190464}
[preflight-trigger : create-openshift-ci-prowjob] 2023/05/23 20:49:32 job failed
```
https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/troubleshooting.md#preflight-trigger

**Comment by jfrancin** [comment]
Let me take a look at why the add-bundle-to-index failed.

**Comment by jfrancin** [comment]
The cause of this failure has been found and resolved. Re-trying the publication step.

**Pull request merged**
